### ISSUE TITLE
Cancel Ripple.

### ISSUE THREAD

**Issue by GuyKahlon** [pixel-ink/PIRipple#1]
Hi, 

I would like to add the ability 'Cancel' Ripple for your PIRipple Class.
I tried to call:
layer.removeAllAnimations()

And also:
for  layer in view.layer.sublayers{
      layer.removeAllAnimations()
}

(From the same UIView I added the Ripple)

But without any success. 
Do you have suggestions for me?

Thanks,
Guy

Great work, By the way :)

**Comment by yoshik** [comment]
Hi,Thank you for using! I am happy.
Thanks reporting. and I can understand this problem. 

## Reason.
PIRipple performed your superview. 
Because, I think this.
- (A) User want to use "Clip to Bounds" for corner radius. so, target uiview setted "view.clipToBounds = ture"
- (B) User do not want to clip Ripple. user should set "view.clipToBounds = false ".
  Opps, It's conflict. but, "Ripple add to SuperView" can solve A and B

## Resolve

Plan 1.
You wait. I add "Cancel Method" about this week.

Plan 2.
You customize your local PIRipple. so, you should to change " isRunSuperView: true " -> " isRunSuperView: false ".

... isRunSuperView flag is private var. sorry.

Plan 3.
You perform " yourview.layer.removeAllAnimations " change to
" yourview.superview.layer.removeAllAnimations " 
but I don't recommend. It offen happens other bug.

Thank you !

**Comment by pixel-ink** [comment]
Hi,Thank you for using! I am happy.
Thanks reporting. and I can understand this problem. 

## Reason.

PIRipple performed your superview. 
Because, I think this.
- (A) User want to use "Clip to Bounds" for corner radius. so, target uiview setted "view.clipToBounds = ture"
- (B) User do not want to clip Ripple. user should set "view.clipToBounds = false ".
- Opps, It's conflict. but, "Ripple add to SuperView" can solve A and B

## Resolve

Plan 1.
You wait. I add "Cancel Method" about this week.

Plan 2.
You customize your local PIRipple. so, you should to change " isRunSuperView: true " -> " isRunSuperView: false ".

... isRunSuperView flag is private var. sorry.

Plan 3.
You perform " yourview.layer.removeAllAnimations " change to
" yourview.superview.layer.removeAllAnimations " 
but I don't recommend. It offen happens problem in other code.

Thank you !

**Comment by GuyKahlon** [comment]
I'll wait, Thank you very much.

You can close the issue if you want.

Thanks man you helped me a lot.

**Comment by pixel-ink** [comment]
Hi, @GuyKahlon .
Try it Podversion 1.1.0.

cancel animation

```
rippleStop()
```

```
Ripple.stop(self.view)
```

Thank you for waiting.

**Comment by GuyKahlon** [comment]
Thanks man :+1:
